# 7.7 `array` Operators

### Arithmetic Operations with `array`s and Individual Numeric Values

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)

In [3]:
numbers

array([1, 2, 3, 4, 5])

In [4]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [6]:
numbers  # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [8]:
numbers += 10

In [9]:
numbers

array([21, 22, 23, 24, 25])

### Broadcasting 

### Arithmetic Operations Between `array`s 

In [10]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [11]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [12]:
numbers * numbers2

array([ 23.1,  48.4,  75.9, 105.6, 137.5])

### Comparing arrays

In [13]:
numbers

array([21, 22, 23, 24, 25])

In [14]:
numbers >= 13

array([ True,  True,  True,  True,  True])

In [15]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [16]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [17]:
numbers == numbers2

array([False, False, False, False, False])

In [18]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [ ]:
Elsa Ghirmazion

In [ ]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################
