In [2]:
# Section 7.2 snippets
import numpy as np

numbers = np.array([2, 3, 5, 7, 11])

type(numbers)

numbers

# Multidimensional Arguments
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Section 7.2 Self Check snippets

# Exercise 2
import numpy as np

np.array([x for x in range(2, 21, 2)])

# Exercise 3
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [6]:
# Section 7.3 snippets
import numpy as np

integers = np.array([[1, 2, 3], [4, 5, 6]])

integers

floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [7]:
# Determining an array’s Element Type
integers.dtype

floats.dtype


dtype('float64')

In [8]:
# Determining an array’s Dimensions
integers.ndim

floats.ndim

integers.shape

floats.shape


(5,)

In [9]:
# Determining an array’s Number of Elements and Element Size
integers.size

integers.itemsize

floats.size

floats.itemsize


8

In [10]:
# Iterating through a Multidimensional array’s Elements
for row in integers:
    for column in row:
        print(column, end='  ')
    print()

for i in integers.flat:
    print(i, end='  ')

1  2  3  
4  5  6  
1  2  3  4  5  6  

In [11]:
# Section 7.3 Self Check snippets

# Exercise 1
import numpy as np

a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

a.ndim

a.shape

(2, 5)

In [ ]:
Elsa Ghiormazion